// config.js
const categoryFiles = [
    { name: "0-模擬問題単語帳", file: "0-模擬問題単語帳.csv" },
    { name: "01-03new_Architecture_Overview", file: "01-03new_Architecture_Overview.csv" },
    { name: "01-03_全体像 - s", file: "01-03_全体像 - s.csv" },
    { name: "04-IAM - g", file: "04-IAM - g.csv" },
    { name: "04new_IAM_SAA_v2", file: "04new_IAM_SAA_v2.csv" },
    { name: "05-VPC - g", file: "05-VPC - g.csv" },
    { name: "05new_VPC_SAA_v2", file: "05new_VPC_SAA_v2.csv" },
    { name: "06-EC2 - g", file: "06-EC2 - g.csv" },
    { name: "06new_EC2_SAA_v2", file: "06new_EC2_SAA_v2.csv" },
    { name: "07-S3 - g", file: "07-S3 - g.csv" },
    { name: "07new_S3_SAA_v2", file: "07new_S3_SAA_v2.csv" },
    { name: "08-Well-Architected Framework - g", file: "08-Well-Architected Framework - g.csv" },
    { name: "08new_Well-Architected_Framework", file: "08new_Well-Architected_Framework.csv" },
    { name: "09-信頼性の設計＆RDS - g", file: "09-信頼性の設計＆RDS - g.csv" },
    { name: "09new_Reliability_RDS_SAA_v2", file: "09new_Reliability_RDS_SAA_v2.csv" },
    { name: "10-Route53 - g", file: "10-Route53 - g.csv" },
    { name: "10new_Route53_SAA_v2", file: "10new_Route53_SAA_v2.csv" },
    { name: "11-データベース - g", file: "11-データベース - g.csv" },
    { name: "11new_Database_SAA_v2", file: "11new_Database_SAA_v2.csv" },
    { name: "12-ストレージとデータ処理と認証 - g", file: "12-ストレージとデータ処理と認証 - g.csv" },
    { name: "12new_Storage_Data_Auth_SAA_v2", file: "12new_Storage_Data_Auth_SAA_v2.csv" },
    { name: "13-サーバレス - g", file: "13-サーバレス - g.csv" },
    { name: "13new_Serverless_SAA_v2", file: "13new_Serverless_SAA_v2.csv" },
    { name: "14-AWSの環境自動化サービス - g", file: "14-AWSの環境自動化サービス - g.csv" },
    { name: "14new_Automation", file: "14new_Automation.csv" },
    { name: "15-セキュリティCloudFront - g", file: "15-セキュリティCloudFront - g.csv" },
    { name: "15new_Security_CloudFront", file: "15new_Security_CloudFront.csv" },
    { name: "16-コスト最適化 - g", file: "16-コスト最適化 - g.csv" },
    { name: "16new_Cost_Optimization", file: "16new_Cost_Optimization.csv" },
    { name: "17-運用上の優秀性 - g", file: "17-運用上の優秀性 - g.csv" },
    { name: "17new_Operational_Excellence", file: "17new_Operational_Excellence.csv" },
    { name: "18-移行と機械学習 - g", file: "18-移行と機械学習 - g.csv" },
    { name: "18new_Migration_ML", file: "18new_Migration_ML.csv" },
    // ...ここに20個分、{ name: "表示名", file: "実際のファイル名.csv" } を並べてください
    { name: "全サービス名 - s", file: "全サービス名 - s.csv" },
];
