// dict.js
const dict = {
    "AWS": "エーダブリューエス",
    "SAA": "エスエーエー",
    "ICT": "アイシーティー",
    "S3": "エススリー",
    "EC2": "イーシーつー",
    "EBS": "イービーエス",
    "VPC": "ブイピーシー",
    "IAM": "アイアム",
    "RDS": "アールディーエス",
    "Lambda": "ラムダ",
    "DynamoDB": "ダイナモディービー",
    "CloudFront": "クラウドフロント",
    "Route 53": "ルートフィフティスリー",
    "ELB": "イーエルビー",
    "ALB": "エーエルビー",
    "NLB": "エヌエルビー",
    "SQS": "エスキューエス",
    "SNS": "エスエヌエス",
    "Kinesis": "キネシス",
    "Redshift": "レッドシフト",
    "Aurora": "オーロラ",
    "CloudWatch": "クラウドウォッチ",
    "CloudTrail": "クラウドトレイル",
    "CloudFormation": "クラウドフォーメーション",
    "Auto Scaling": "オートスケーリング",
    "ASG": "エーエスジー",
    "Glacier": "グレイシア",
    "EFS": "イーエフエス",
    "Storage Gateway": "ストレージゲートウェイ",
    "Direct Connect": "ダイレクトコネクト",
    "DX": "ディーエックス",
    "NAT Gateway": "ナットゲートウェイ",
    "ACM": "エーシーエム",
    "KMS": "ケーエムエス",
    "Fargate": "ファーゲート",
    "ECS": "イーシーエス",
    "EKS": "イーケーエス",
    "WAF": "ワフ",
    "Shield": "シールド",
    "Config": "コンフィグ",
    "Organizations": "オーガニゼーションズ",
    "FSx": "エフエスエックス",
    "Inspector": "インスペクター",
    "GuardDuty": "ガードデューティ",
    "Macie": "メイシー",
    "Artifact": "アーティファクト",
    "X-Ray": "エックスレイ"
};
